[project]
name = "hurricane_net"
version = "0.1.4"
authors = [
  { name="fluids", email="husmani@fluids.ai" },
]
description = "A Python package that provides tropical storm and hurricane data, tools, and artificial intelligence."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "CC0-1.0"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "pandas",
    "langchain"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
hurricane_net = []
"hurricane_net.prompts" = ["*.txt"]

[project.urls]
Homepage = "https://github.com/hammad93/hurricane-net"
Issues = "https://github.com/hammad93/hurricane-agent/issues"